// examples/vue/useHotkey/src/App.vue
<script setup lang="ts">
import { TanStackDevtools } from '@tanstack/vue-devtools'
import { HotkeysProvider, formatForDisplay, useHotkey } from '@tanstack/vue-hotkeys'
import { HotkeysDevtoolsPanel } from '@tanstack/vue-hotkeys-devtools'
import type { Hotkey } from '@tanstack/vue-hotkeys'
import { nextTick, ref, watch } from 'vue'

const lastHotkey = ref<Hotkey | null>(null)
const saveCount = ref(0)
const incrementCount = ref(0)
const enabled = ref(true)
const activeTab = ref(1)
const navigationCount = ref(0)
const functionKeyCount = ref(0)
const multiModifierCount = ref(0)
const editingKeyCount = ref(0)

const modalOpen = ref(false)
const editorContent = ref('')
const sidebarShortcutCount = ref(0)
const modalShortcutCount = ref(0)
const editorShortcutCount = ref(0)

const sidebarRef = ref<HTMLDivElement | null>(null)
const modalRef = ref<HTMLDivElement | null>(null)
const editorRef = ref<HTMLTextAreaElement | null>(null)
const plugins = [{ name: 'TanStack Hotkeys', component: HotkeysDevtoolsPanel }]

useHotkey('Mod+S', (_event, { hotkey, parsedHotkey }) => {
  lastHotkey.value = hotkey
  saveCount.value++
  console.log('Hotkey triggered:', hotkey)
  console.log('Parsed hotkey:', parsedHotkey)
})

useHotkey(
  'Mod+K',
  (_event, { hotkey }) => {
    lastHotkey.value = hotkey
    incrementCount.value++
  },
  { requireReset: true },
)

useHotkey(
  'Mod+E',
  (_event, { hotkey }) => {
    lastHotkey.value = hotkey
    alert('This hotkey can be toggled!')
  },
  { enabled },
)

useHotkey('Mod+1', () => {
  lastHotkey.value = 'Mod+1'
  activeTab.value = 1
})
useHotkey('Mod+2', () => {
  lastHotkey.value = 'Mod+2'
  activeTab.value = 2
})
useHotkey('Mod+3', () => {
  lastHotkey.value = 'Mod+3'
  activeTab.value = 3
})
useHotkey('Mod+4', () => {
  lastHotkey.value = 'Mod+4'
  activeTab.value = 4
})
useHotkey('Mod+5', () => {
  lastHotkey.value = 'Mod+5'
  activeTab.value = 5
})

useHotkey('Shift+ArrowUp', () => {
  lastHotkey.value = 'Shift+ArrowUp'
  navigationCount.value++
})
useHotkey('Shift+ArrowDown', () => {
  lastHotkey.value = 'Shift+ArrowDown'
  navigationCount.value++
})
useHotkey('Alt+ArrowLeft', () => {
  lastHotkey.value = 'Alt+ArrowLeft'
  navigationCount.value++
})
useHotkey('Alt+ArrowRight', () => {
  lastHotkey.value = 'Alt+ArrowRight'
  navigationCount.value++
})
useHotkey('Mod+Home', () => {
  lastHotkey.value = 'Mod+Home'
  navigationCount.value++
})
useHotkey('Mod+End', () => {
  lastHotkey.value = 'Mod+End'
  navigationCount.value++
})
useHotkey('Control+PageUp', () => {
  lastHotkey.value = 'Control+PageUp'
  navigationCount.value++
})
useHotkey('Control+PageDown', () => {
  lastHotkey.value = 'Control+PageDown'
  navigationCount.value++
})

useHotkey('Meta+F4', () => {
  lastHotkey.value = 'Alt+F4'
  functionKeyCount.value++
  alert('Alt+F4 pressed (normally closes window)')
})
useHotkey('Control+F5', () => {
  lastHotkey.value = 'Control+F5'
  functionKeyCount.value++
})
useHotkey('Mod+F1', () => {
  lastHotkey.value = 'Mod+F1'
  functionKeyCount.value++
})
useHotkey('Shift+F10', () => {
  lastHotkey.value = 'Shift+F10'
  functionKeyCount.value++
})

useHotkey('Mod+Shift+S', () => {
  lastHotkey.value = 'Mod+Shift+S'
  multiModifierCount.value++
})
useHotkey('Mod+Shift+Z', () => {
  lastHotkey.value = 'Mod+Shift+Z'
  multiModifierCount.value++
})
useHotkey({ key: 'A', ctrl: true, alt: true }, () => {
  lastHotkey.value = 'Control+Alt+A'
  multiModifierCount.value++
})
useHotkey('Control+Shift+N', () => {
  lastHotkey.value = 'Control+Shift+N'
  multiModifierCount.value++
})
useHotkey('Mod+Alt+T', () => {
  lastHotkey.value = 'Mod+Alt+T'
  multiModifierCount.value++
})
useHotkey('Control+Alt+Shift+X', () => {
  lastHotkey.value = 'Control+Alt+Shift+X'
  multiModifierCount.value++
})

useHotkey('Mod+Enter', () => {
  lastHotkey.value = 'Mod+Enter'
  editingKeyCount.value++
})
useHotkey('Shift+Enter', () => {
  lastHotkey.value = 'Shift+Enter'
  editingKeyCount.value++
})
useHotkey('Mod+Backspace', () => {
  lastHotkey.value = 'Mod+Backspace'
  editingKeyCount.value++
})
useHotkey('Mod+Delete', () => {
  lastHotkey.value = 'Mod+Delete'
  editingKeyCount.value++
})
useHotkey('Control+Tab', () => {
  lastHotkey.value = 'Control+Tab'
  editingKeyCount.value++
})
useHotkey('Shift+Tab', () => {
  lastHotkey.value = 'Shift+Tab'
  editingKeyCount.value++
})
useHotkey('Mod+Space', () => {
  lastHotkey.value = 'Mod+Space'
  editingKeyCount.value++
})

useHotkey({ key: 'Escape' }, () => {
  lastHotkey.value = null
  saveCount.value = 0
  incrementCount.value = 0
  navigationCount.value = 0
  functionKeyCount.value = 0
  multiModifierCount.value = 0
  editingKeyCount.value = 0
  activeTab.value = 1
})

useHotkey('F12', () => {
  lastHotkey.value = 'F12'
  functionKeyCount.value++
})

watch(modalOpen, async (isOpen) => {
  if (isOpen) {
    await nextTick()
    modalRef.value?.focus()
  }
})

useHotkey(
  'Mod+B',
  () => {
    lastHotkey.value = 'Mod+B'
    sidebarShortcutCount.value++
    alert(
      'Sidebar shortcut triggered! This only works when the sidebar area is focused.',
    )
  },
  { target: sidebarRef },
)

useHotkey(
  'Mod+N',
  () => {
    lastHotkey.value = 'Mod+N'
    sidebarShortcutCount.value++
  },
  { target: sidebarRef },
)

useHotkey(
  'Escape',
  () => {
    lastHotkey.value = 'Escape'
    modalShortcutCount.value++
    modalOpen.value = false
  },
  { target: modalRef, enabled: modalOpen },
)

useHotkey(
  'Mod+Enter',
  () => {
    lastHotkey.value = 'Mod+Enter'
    modalShortcutCount.value++
    alert('Modal submit shortcut!')
  },
  { target: modalRef, enabled: modalOpen },
)

useHotkey(
  'Mod+S',
  () => {
    lastHotkey.value = 'Mod+S'
    editorShortcutCount.value++
    alert(
      `Editor content saved: "${editorContent.value.substring(0, 50)}${editorContent.value.length > 50 ? '...' : ''}"`,
    )
  },
  { target: editorRef },
)

useHotkey(
  'Mod+/',
  () => {
    lastHotkey.value = 'Mod+/'
    editorShortcutCount.value++
    editorContent.value += '\n// Comment added via shortcut'
  },
  { target: editorRef },
)

useHotkey(
  'Mod+K',
  () => {
    lastHotkey.value = 'Mod+K'
    editorShortcutCount.value++
    editorContent.value = ''
  },
  { target: editorRef },
)

const basicCode = `useHotkey('Mod+S', (_event, { hotkey, parsedHotkey }) => {
  console.log('Hotkey:', hotkey)
  console.log('Parsed:', parsedHotkey)
})`

const requireResetCode = `useHotkey(
  'Mod+K',
  (event, { hotkey }) => {
    setCount(c => c + 1)
  },
  { requireReset: true }
)`

const conditionalCode = `const [enabled, setEnabled] = useState(true)

useHotkey(
  'Mod+E',
  (event, { hotkey }) => {
    alert('Triggered!')
  },
  { enabled }
)`

const numberCode = `useHotkey('Mod+1', () => setActiveTab(1))
useHotkey('Mod+2', () => setActiveTab(2))`

const navigationCode = `useHotkey('Shift+ArrowUp', () => selectUp())
useHotkey('Alt+ArrowLeft', () => navigateBack())
useHotkey('Mod+Home', () => goToStart())
useHotkey('Control+PageUp', () => previousPage())`

const functionCode = `useHotkey('Alt+F4', () => closeWindow())
useHotkey('Control+F5', () => hardRefresh())
useHotkey('Mod+F1', () => showHelp())
useHotkey('F12', () => openDevTools())`

const multiModifierCode = `useHotkey('Mod+Shift+S', () => saveAs())
useHotkey('Mod+Shift+Z', () => redo())
useHotkey('Control+Alt+A', () => specialAction())
useHotkey('Control+Alt+Shift+X', () => complexAction())`

const editingCode = `useHotkey('Mod+Enter', () => submitForm())
useHotkey('Shift+Enter', () => insertNewline())
useHotkey('Mod+Backspace', () => deleteWord())
useHotkey('Control+Tab', () => nextTab())
useHotkey('Mod+Space', () => toggle())`

const scopedCode = `// Scoped to a ref
const sidebarRef = useRef<HTMLDivElement>(null)

useHotkey(
  'Mod+B',
  () => {
    console.log('Sidebar shortcut!')
  },
  { target: sidebarRef }
)

// Scoped to a modal (only when open)
const modalRef = useRef<HTMLDivElement>(null)
const [isOpen, setIsOpen] = useState(false)

useHotkey(
  'Escape',
  () => setIsOpen(false),
  { target: modalRef, enabled: isOpen }
)

// Scoped to an editor
const editorRef = useRef<HTMLTextAreaElement>(null)

useHotkey(
  'Mod+S',
  () => saveEditorContent(),
  { target: editorRef }
)`
</script>

<template>
  <HotkeysProvider>
    <div class="app">
      <header>
        <h1>useHotkey</h1>
        <p>
          Register keyboard shortcuts with callback context containing the
          hotkey and parsed hotkey information.
        </p>
      </header>

      <main>
        <section class="demo-section">
          <h2>Basic Hotkey</h2>
          <p>
            Press <kbd>{{ formatForDisplay('Mod+S') }}</kbd> to trigger
          </p>
          <div class="counter">Save triggered: {{ saveCount }}x</div>
          <pre class="code-block">{{ basicCode }}</pre>
        </section>

        <section class="demo-section">
          <h2>With requireReset</h2>
          <p>
            Hold <kbd>{{ formatForDisplay('Mod+K') }}</kbd> — only increments once
            until you release all keys
          </p>
          <div class="counter">Increment: {{ incrementCount }}</div>
          <p class="hint">
            This prevents repeated triggering while holding the keys down.
            Release all keys to allow re-triggering.
          </p>
          <pre class="code-block">{{ requireResetCode }}</pre>
        </section>

        <section class="demo-section">
          <h2>Conditional Hotkey</h2>
          <p>
            <kbd>{{ formatForDisplay('Mod+E') }}</kbd> is currently
            <strong> {{ enabled ? 'enabled' : 'disabled' }}</strong>
          </p>
          <button @click="enabled = !enabled">
            {{ enabled ? 'Disable' : 'Enable' }} Hotkey
          </button>
          <pre class="code-block">{{ conditionalCode }}</pre>
        </section>

        <section class="demo-section">
          <h2>Number Key Combinations</h2>
          <p>Common for tab/section switching:</p>
          <div class="hotkey-grid">
            <div><kbd>{{ formatForDisplay('Mod+1') }}</kbd> → Tab 1</div>
            <div><kbd>{{ formatForDisplay('Mod+2') }}</kbd> → Tab 2</div>
            <div><kbd>{{ formatForDisplay('Mod+3') }}</kbd> → Tab 3</div>
            <div><kbd>{{ formatForDisplay('Mod+4') }}</kbd> → Tab 4</div>
            <div><kbd>{{ formatForDisplay('Mod+5') }}</kbd> → Tab 5</div>
          </div>
          <div class="counter">Active Tab: {{ activeTab }}</div>
          <pre class="code-block">{{ numberCode }}</pre>
        </section>

        <section class="demo-section">
          <h2>Navigation Key Combinations</h2>
          <p>Selection and navigation shortcuts:</p>
          <div class="hotkey-grid">
            <div><kbd>{{ formatForDisplay('Shift+ArrowUp') }}</kbd> — Select up</div>
            <div>
              <kbd>{{ formatForDisplay('Shift+ArrowDown') }}</kbd> — Select down
            </div>
            <div>
              <kbd>{{ formatForDisplay('Alt+ArrowLeft') }}</kbd> — Navigate back
            </div>
            <div>
              <kbd>{{ formatForDisplay('Alt+ArrowRight') }}</kbd> — Navigate
              forward
            </div>
            <div><kbd>{{ formatForDisplay('Mod+Home') }}</kbd> — Go to start</div>
            <div><kbd>{{ formatForDisplay('Mod+End') }}</kbd> — Go to end</div>
            <div>
              <kbd>{{ formatForDisplay('Control+PageUp') }}</kbd> — Previous page
            </div>
            <div>
              <kbd>{{ formatForDisplay('Control+PageDown') }}</kbd> — Next page
            </div>
          </div>
          <div class="counter">Navigation triggered: {{ navigationCount }}x</div>
          <pre class="code-block">{{ navigationCode }}</pre>
        </section>

        <section class="demo-section">
          <h2>Function Key Combinations</h2>
          <p>System and application shortcuts:</p>
          <div class="hotkey-grid">
            <div><kbd>{{ formatForDisplay('Alt+F4') }}</kbd> — Close window</div>
            <div>
              <kbd>{{ formatForDisplay('Control+F5') }}</kbd> — Hard refresh
            </div>
            <div><kbd>{{ formatForDisplay('Mod+F1') }}</kbd> — Help</div>
            <div><kbd>{{ formatForDisplay('Shift+F10') }}</kbd> — Context menu</div>
            <div><kbd>{{ formatForDisplay('F12') }}</kbd> — DevTools</div>
          </div>
          <div class="counter">Function keys triggered: {{ functionKeyCount }}x</div>
          <pre class="code-block">{{ functionCode }}</pre>
        </section>

        <section class="demo-section">
          <h2>Multi-Modifier Combinations</h2>
          <p>Complex shortcuts with multiple modifiers:</p>
          <div class="hotkey-grid">
            <div><kbd>{{ formatForDisplay('Mod+Shift+S') }}</kbd> — Save As</div>
            <div><kbd>{{ formatForDisplay('Mod+Shift+Z') }}</kbd> — Redo</div>
            <div>
              <kbd>{{ formatForDisplay('Control+Alt+A') }}</kbd> — Special action
            </div>
            <div>
              <kbd>{{ formatForDisplay('Control+Shift+N') }}</kbd> — New incognito
            </div>
            <div><kbd>{{ formatForDisplay('Mod+Alt+T') }}</kbd> — Toggle theme</div>
            <div>
              <kbd>{{ formatForDisplay('Control+Alt+Shift+X') }}</kbd> — Triple
              modifier
            </div>
          </div>
          <div class="counter">
            Multi-modifier triggered: {{ multiModifierCount }}x
          </div>
          <pre class="code-block">{{ multiModifierCode }}</pre>
        </section>

        <section class="demo-section">
          <h2>Editing Key Combinations</h2>
          <p>Text editing and form shortcuts:</p>
          <div class="hotkey-grid">
            <div><kbd>{{ formatForDisplay('Mod+Enter') }}</kbd> — Submit form</div>
            <div><kbd>{{ formatForDisplay('Shift+Enter') }}</kbd> — New line</div>
            <div>
              <kbd>{{ formatForDisplay('Mod+Backspace') }}</kbd> — Delete word
            </div>
            <div>
              <kbd>{{ formatForDisplay('Mod+Delete') }}</kbd> — Delete forward
            </div>
            <div><kbd>{{ formatForDisplay('Control+Tab') }}</kbd> — Next tab</div>
            <div>
              <kbd>{{ formatForDisplay('Shift+Tab') }}</kbd> — Previous field
            </div>
            <div><kbd>{{ formatForDisplay('Mod+Space') }}</kbd> — Toggle</div>
          </div>
          <div class="counter">Editing keys triggered: {{ editingKeyCount }}x</div>
          <pre class="code-block">{{ editingCode }}</pre>
        </section>

        <div v-if="lastHotkey" class="info-box">
          <strong>Last triggered:</strong> {{ formatForDisplay(lastHotkey) }}
        </div>

        <p class="hint">Press <kbd>Escape</kbd> to reset all counters</p>

        <section class="demo-section scoped-section">
          <h2>Scoped Keyboard Shortcuts</h2>
          <p>
            Shortcuts can be scoped to specific DOM elements using the
            <code>target</code> option. This allows different shortcuts to work
            in different parts of your application.
          </p>

          <div class="scoped-grid">
            <div ref="sidebarRef" class="scoped-area" tabindex="0">
              <h3>Sidebar (Scoped Area)</h3>
              <p>Click here to focus, then try:</p>
              <div class="hotkey-list">
                <div>
                  <kbd>{{ formatForDisplay('Mod+B') }}</kbd> — Trigger sidebar
                  action
                </div>
                <div><kbd>{{ formatForDisplay('Mod+N') }}</kbd> — New item</div>
              </div>
              <div class="counter">Sidebar shortcuts: {{ sidebarShortcutCount }}x</div>
              <p class="hint">
                These shortcuts only work when this sidebar area is focused or
                contains focus.
              </p>
            </div>

            <div class="scoped-area">
              <h3>Modal Dialog</h3>
              <button @click="modalOpen = true">Open Modal</button>
              <div v-if="modalOpen" class="modal-overlay" @click="modalOpen = false">
                <div
                  ref="modalRef"
                  class="modal-content"
                  tabindex="0"
                  @click.stop
                >
                  <h3>Modal Dialog (Scoped)</h3>
                  <p>Try these shortcuts while modal is open:</p>
                  <div class="hotkey-list">
                    <div><kbd>{{ formatForDisplay('Escape') }}</kbd> — Close modal</div>
                    <div>
                      <kbd>{{ formatForDisplay('Mod+Enter') }}</kbd> — Submit
                    </div>
                  </div>
                  <div class="counter">Modal shortcuts: {{ modalShortcutCount }}x</div>
                  <p class="hint">
                    These shortcuts only work when the modal is open and focused.
                    The Escape key here won't conflict with the global Escape
                    handler.
                  </p>
                  <button @click="modalOpen = false">Close</button>
                </div>
              </div>
            </div>

            <div class="scoped-area">
              <h3>Text Editor (Scoped)</h3>
              <p>Focus the editor below and try:</p>
              <div class="hotkey-list">
                <div>
                  <kbd>{{ formatForDisplay('Mod+S') }}</kbd> — Save editor content
                </div>
                <div>
                  <kbd>{{ formatForDisplay('Mod+/') }}</kbd> — Add comment
                </div>
                <div><kbd>{{ formatForDisplay('Mod+K') }}</kbd> — Clear editor</div>
              </div>
              <textarea
                ref="editorRef"
                v-model="editorContent"
                class="scoped-editor"
                placeholder="Focus here and try the shortcuts above..."
                rows="8"
              />
              <div class="counter">Editor shortcuts: {{ editorShortcutCount }}x</div>
              <p class="hint">
                These shortcuts only work when the editor is focused. Notice that
                <kbd>{{ formatForDisplay('Mod+S') }}</kbd> here doesn't conflict
                with the global <kbd>{{ formatForDisplay('Mod+S') }}</kbd>
                shortcut.
              </p>
            </div>
          </div>

          <pre class="code-block">{{ scopedCode }}</pre>
        </section>
      </main>

      <TanStackDevtools :plugins="plugins" />
    </div>
  </HotkeysProvider>
</template>

// examples/angular/injectHotkey/src/app/app.component.ts
import { Component, ElementRef, signal, viewChild } from '@angular/core'
import {
  formatForDisplay,
  injectHotkey,
  type Hotkey,
} from '@tanstack/angular-hotkeys'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [],
  templateUrl: './app.component.html',
})
export class AppComponent {
  protected readonly lastHotkey = signal<Hotkey | null>(null)
  protected readonly saveCount = signal(0)
  protected readonly incrementCount = signal(0)
  protected readonly enabled = signal(true)
  protected readonly activeTab = signal(1)
  protected readonly navigationCount = signal(0)
  protected readonly functionKeyCount = signal(0)
  protected readonly multiModifierCount = signal(0)
  protected readonly editingKeyCount = signal(0)

  protected readonly modalOpen = signal(false)
  protected readonly editorContent = signal('')
  protected readonly sidebarShortcutCount = signal(0)
  protected readonly modalShortcutCount = signal(0)
  protected readonly editorShortcutCount = signal(0)

  private readonly sidebarRef =
    viewChild<ElementRef<HTMLDivElement>>('sidebarRef')
  private readonly modalRef = viewChild<ElementRef<HTMLDivElement>>('modalRef')
  private readonly editorRef =
    viewChild<ElementRef<HTMLTextAreaElement>>('editorRef')

  constructor() {
    injectHotkey('Mod+S', (_event, { hotkey }) => {
      this.lastHotkey.set(hotkey)
      this.saveCount.update((c) => c + 1)
    })

    injectHotkey(
      'Mod+K',
      (_event, { hotkey }) => {
        this.lastHotkey.set(hotkey)
        this.incrementCount.update((c) => c + 1)
      },
      { requireReset: true },
    )

    injectHotkey(
      'Mod+E',
      (_event, { hotkey }) => {
        this.lastHotkey.set(hotkey)
        alert('This hotkey can be toggled!')
      },
      () => ({ enabled: this.enabled() }),
    )

    injectHotkey('Mod+1', () => {
      this.lastHotkey.set('Mod+1')
      this.activeTab.set(1)
    })
    injectHotkey('Mod+2', () => {
      this.lastHotkey.set('Mod+2')
      this.activeTab.set(2)
    })
    injectHotkey('Mod+3', () => {
      this.lastHotkey.set('Mod+3')
      this.activeTab.set(3)
    })
    injectHotkey('Mod+4', () => {
      this.lastHotkey.set('Mod+4')
      this.activeTab.set(4)
    })
    injectHotkey('Mod+5', () => {
      this.lastHotkey.set('Mod+5')
      this.activeTab.set(5)
    })

    injectHotkey('Shift+ArrowUp', () => {
      this.lastHotkey.set('Shift+ArrowUp')
      this.navigationCount.update((c) => c + 1)
    })
    injectHotkey('Shift+ArrowDown', () => {
      this.lastHotkey.set('Shift+ArrowDown')
      this.navigationCount.update((c) => c + 1)
    })
    injectHotkey('Alt+ArrowLeft', () => {
      this.lastHotkey.set('Alt+ArrowLeft')
      this.navigationCount.update((c) => c + 1)
    })
    injectHotkey('Alt+ArrowRight', () => {
      this.lastHotkey.set('Alt+ArrowRight')
      this.navigationCount.update((c) => c + 1)
    })
    injectHotkey('Mod+Home', () => {
      this.lastHotkey.set('Mod+Home')
      this.navigationCount.update((c) => c + 1)
    })
    injectHotkey('Mod+End', () => {
      this.lastHotkey.set('Mod+End')
      this.navigationCount.update((c) => c + 1)
    })
    injectHotkey('Control+PageUp', () => {
      this.lastHotkey.set('Control+PageUp')
      this.navigationCount.update((c) => c + 1)
    })
    injectHotkey('Control+PageDown', () => {
      this.lastHotkey.set('Control+PageDown')
      this.navigationCount.update((c) => c + 1)
    })

    injectHotkey('Meta+F4', () => {
      this.lastHotkey.set('Alt+F4')
      this.functionKeyCount.update((c) => c + 1)
      alert('Alt+F4 pressed (normally closes window)')
    })
    injectHotkey('Control+F5', () => {
      this.lastHotkey.set('Control+F5')
      this.functionKeyCount.update((c) => c + 1)
    })
    injectHotkey('Mod+F1', () => {
      this.lastHotkey.set('Mod+F1')
      this.functionKeyCount.update((c) => c + 1)
    })
    injectHotkey('Shift+F10', () => {
      this.lastHotkey.set('Shift+F10')
      this.functionKeyCount.update((c) => c + 1)
    })

    injectHotkey('Mod+Shift+S', () => {
      this.lastHotkey.set('Mod+Shift+S')
      this.multiModifierCount.update((c) => c + 1)
    })
    injectHotkey('Mod+Shift+Z', () => {
      this.lastHotkey.set('Mod+Shift+Z')
      this.multiModifierCount.update((c) => c + 1)
    })
    injectHotkey({ key: 'A', ctrl: true, alt: true }, () => {
      this.lastHotkey.set('Control+Alt+A')
      this.multiModifierCount.update((c) => c + 1)
    })
    injectHotkey('Control+Shift+N', () => {
      this.lastHotkey.set('Control+Shift+N')
      this.multiModifierCount.update((c) => c + 1)
    })
    injectHotkey('Mod+Alt+T', () => {
      this.lastHotkey.set('Mod+Alt+T')
      this.multiModifierCount.update((c) => c + 1)
    })
    injectHotkey('Control+Alt+Shift+X', () => {
      this.lastHotkey.set('Control+Alt+Shift+X')
      this.multiModifierCount.update((c) => c + 1)
    })

    injectHotkey('Mod+Enter', () => {
      this.lastHotkey.set('Mod+Enter')
      this.editingKeyCount.update((c) => c + 1)
    })
    injectHotkey('Shift+Enter', () => {
      this.lastHotkey.set('Shift+Enter')
      this.editingKeyCount.update((c) => c + 1)
    })
    injectHotkey('Mod+Backspace', () => {
      this.lastHotkey.set('Mod+Backspace')
      this.editingKeyCount.update((c) => c + 1)
    })
    injectHotkey('Mod+Delete', () => {
      this.lastHotkey.set('Mod+Delete')
      this.editingKeyCount.update((c) => c + 1)
    })
    injectHotkey('Control+Tab', () => {
      this.lastHotkey.set('Control+Tab')
      this.editingKeyCount.update((c) => c + 1)
    })
    injectHotkey('Shift+Tab', () => {
      this.lastHotkey.set('Shift+Tab')
      this.editingKeyCount.update((c) => c + 1)
    })
    injectHotkey('Mod+Space', () => {
      this.lastHotkey.set('Mod+Space')
      this.editingKeyCount.update((c) => c + 1)
    })

    injectHotkey({ key: 'Escape' }, () => {
      this.lastHotkey.set(null)
      this.saveCount.set(0)
      this.incrementCount.set(0)
      this.navigationCount.set(0)
      this.functionKeyCount.set(0)
      this.multiModifierCount.set(0)
      this.editingKeyCount.set(0)
      this.activeTab.set(1)
    })
    injectHotkey('F12', () => {
      this.lastHotkey.set('F12')
      this.functionKeyCount.update((c) => c + 1)
    })

    // Scoped: sidebar (Solid-style getter)
    injectHotkey(
      'Mod+B',
      () => {
        this.lastHotkey.set('Mod+B')
        this.sidebarShortcutCount.update((c) => c + 1)
        alert(
          'Sidebar shortcut triggered! This only works when the sidebar area is focused.',
        )
      },
      () => ({ target: this.sidebarRef()?.nativeElement ?? null }),
    )
    injectHotkey(
      'Mod+N',
      () => {
        this.lastHotkey.set('Mod+N')
        this.sidebarShortcutCount.update((c) => c + 1)
      },
      () => ({ target: this.sidebarRef()?.nativeElement ?? null }),
    )

    // Scoped: modal (Solid-style getter)
    injectHotkey(
      'Escape',
      () => {
        this.lastHotkey.set('Escape')
        this.modalShortcutCount.update((c) => c + 1)
        this.modalOpen.set(false)
      },
      () => ({
        target: this.modalRef()?.nativeElement ?? null,
        enabled: this.modalOpen(),
      }),
    )
    injectHotkey(
      'Mod+Enter',
      () => {
        this.lastHotkey.set('Mod+Enter')
        this.modalShortcutCount.update((c) => c + 1)
        alert('Modal submit shortcut!')
      },
      () => ({
        target: this.modalRef()?.nativeElement ?? null,
        enabled: this.modalOpen(),
      }),
    )

    // Scoped: editor (Solid-style getter)
    injectHotkey(
      'Mod+S',
      () => {
        this.lastHotkey.set('Mod+S')
        this.editorShortcutCount.update((c) => c + 1)
        const content = this.editorContent()
        alert(
          `Editor content saved: "${content.substring(0, 50)}${content.length > 50 ? '...' : ''}"`,
        )
      },
      () => ({ target: this.editorRef()?.nativeElement ?? null }),
    )
    injectHotkey(
      'Mod+/',
      () => {
        this.lastHotkey.set('Mod+/')
        this.editorShortcutCount.update((c) => c + 1)
        this.editorContent.update(
          (prev) => prev + '\n// Comment added via shortcut',
        )
      },
      () => ({ target: this.editorRef()?.nativeElement ?? null }),
    )
    injectHotkey(
      'Mod+K',
      () => {
        this.lastHotkey.set('Mod+K')
        this.editorShortcutCount.update((c) => c + 1)
        this.editorContent.set('')
      },
      () => ({ target: this.editorRef()?.nativeElement ?? null }),
    )
  }

  protected formatForDisplay = formatForDisplay

  protected openModal(): void {
    this.modalOpen.set(true)
  }

  protected closeModal(): void {
    this.modalOpen.set(false)
  }

  protected closeModalOverlay(): void {
    this.modalOpen.set(false)
  }

  protected onModalContentClick(event: Event): void {
    event.stopPropagation()
  }

  protected onEditorInput(event: Event): void {
    const el = event.target as HTMLTextAreaElement
    this.editorContent.set(el.value)
  }
}

<div class="app">
  <header>
    <h1>injectHotkey</h1>
    <p>
      Register keyboard shortcuts with callback context containing the hotkey
      and parsed hotkey information.
    </p>
  </header>

  <main>
    <section class="demo-section">
      <h2>Basic Hotkey</h2>
      <p>
        Press <kbd>{{ formatForDisplay('Mod+S') }}</kbd> to trigger
      </p>
      <div class="counter">Save triggered: {{ saveCount() }}x</div>
      <pre class="code-block">
injectHotkey('Mod+S', (_event, &#123; hotkey, parsedHotkey &#125;) => &#123;
  console.log('Hotkey:', hotkey)
  console.log('Parsed:', parsedHotkey)
&#125;)</pre
      >
    </section>

    <section class="demo-section">
      <h2>With requireReset</h2>
      <p>
        Hold <kbd>{{ formatForDisplay('Mod+K') }}</kbd> — only increments once
        until you release all keys
      </p>
      <div class="counter">Increment: {{ incrementCount() }}</div>
      <p class="hint">
        This prevents repeated triggering while holding the keys down. Release
        all keys to allow re-triggering.
      </p>
      <pre class="code-block">
injectHotkey(
  'Mod+K',
  (event, &#123; hotkey &#125;) => &#123;
    this.incrementCount.update(c => c + 1)
  &#125;,
  &#123; requireReset: true &#125;
)</pre
      >
    </section>

    <section class="demo-section">
      <h2>Conditional Hotkey</h2>
      <p>
        <kbd>{{ formatForDisplay('Mod+E') }}</kbd> is currently
        <strong>{{ enabled() ? 'enabled' : 'disabled' }}</strong>
      </p>
      <button type="button" (click)="enabled.set(!enabled())">
        {{ enabled() ? 'Disable' : 'Enable' }} Hotkey
      </button>
      <pre class="code-block">
protected readonly enabled = signal(true)
protected readonly modEOptions = computed(() => (&#123; enabled: this.enabled() &#125;))

injectHotkey(
  'Mod+E',
  (event, &#123; hotkey &#125;) => &#123; alert('Triggered!') &#125;,
  this.modEOptions
)</pre
      >
    </section>

    <section class="demo-section">
      <h2>Number Key Combinations</h2>
      <p>Common for tab/section switching:</p>
      <div class="hotkey-grid">
        <div>
          <kbd>{{ formatForDisplay('Mod+1') }}</kbd> → Tab 1
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+2') }}</kbd> → Tab 2
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+3') }}</kbd> → Tab 3
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+4') }}</kbd> → Tab 4
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+5') }}</kbd> → Tab 5
        </div>
      </div>
      <div class="counter">Active Tab: {{ activeTab() }}</div>
      <pre class="code-block">
injectHotkey('Mod+1', () => this.activeTab.set(1))
injectHotkey('Mod+2', () => this.activeTab.set(2))</pre
      >
    </section>

    <section class="demo-section">
      <h2>Navigation Key Combinations</h2>
      <p>Selection and navigation shortcuts:</p>
      <div class="hotkey-grid">
        <div>
          <kbd>{{ formatForDisplay('Shift+ArrowUp') }}</kbd> — Select up
        </div>
        <div>
          <kbd>{{ formatForDisplay('Shift+ArrowDown') }}</kbd> — Select down
        </div>
        <div>
          <kbd>{{ formatForDisplay('Alt+ArrowLeft') }}</kbd> — Navigate back
        </div>
        <div>
          <kbd>{{ formatForDisplay('Alt+ArrowRight') }}</kbd> — Navigate forward
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+Home') }}</kbd> — Go to start
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+End') }}</kbd> — Go to end
        </div>
        <div>
          <kbd>{{ formatForDisplay('Control+PageUp') }}</kbd> — Previous page
        </div>
        <div>
          <kbd>{{ formatForDisplay('Control+PageDown') }}</kbd> — Next page
        </div>
      </div>
      <div class="counter">Navigation triggered: {{ navigationCount() }}x</div>
      <pre class="code-block">
injectHotkey('Shift+ArrowUp', () => selectUp())
injectHotkey('Alt+ArrowLeft', () => navigateBack())
injectHotkey('Mod+Home', () => goToStart())
injectHotkey('Control+PageUp', () => previousPage())</pre
      >
    </section>

    <section class="demo-section">
      <h2>Function Key Combinations</h2>
      <p>System and application shortcuts:</p>
      <div class="hotkey-grid">
        <div>
          <kbd>{{ formatForDisplay('Alt+F4') }}</kbd> — Close window
        </div>
        <div>
          <kbd>{{ formatForDisplay('Control+F5') }}</kbd> — Hard refresh
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+F1') }}</kbd> — Help
        </div>
        <div>
          <kbd>{{ formatForDisplay('Shift+F10') }}</kbd> — Context menu
        </div>
        <div>
          <kbd>{{ formatForDisplay('F12') }}</kbd> — DevTools
        </div>
      </div>
      <div class="counter">
        Function keys triggered: {{ functionKeyCount() }}x
      </div>
      <pre class="code-block">
injectHotkey('Alt+F4', () => closeWindow())
injectHotkey('Control+F5', () => hardRefresh())
injectHotkey('Mod+F1', () => showHelp())
injectHotkey('F12', () => openDevTools())</pre
      >
    </section>

    <section class="demo-section">
      <h2>Multi-Modifier Combinations</h2>
      <p>Complex shortcuts with multiple modifiers:</p>
      <div class="hotkey-grid">
        <div>
          <kbd>{{ formatForDisplay('Mod+Shift+S') }}</kbd> — Save As
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+Shift+Z') }}</kbd> — Redo
        </div>
        <div>
          <kbd>{{ formatForDisplay('Control+Alt+A') }}</kbd> — Special action
        </div>
        <div>
          <kbd>{{ formatForDisplay('Control+Shift+N') }}</kbd> — New incognito
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+Alt+T') }}</kbd> — Toggle theme
        </div>
        <div>
          <kbd>{{ formatForDisplay('Control+Alt+Shift+X') }}</kbd> — Triple
          modifier
        </div>
      </div>
      <div class="counter">
        Multi-modifier triggered: {{ multiModifierCount() }}x
      </div>
      <pre class="code-block">
injectHotkey('Mod+Shift+S', () => saveAs())
injectHotkey('Mod+Shift+Z', () => redo())
injectHotkey('Control+Alt+A', () => specialAction())
injectHotkey('Control+Alt+Shift+X', () => complexAction())</pre
      >
    </section>

    <section class="demo-section">
      <h2>Editing Key Combinations</h2>
      <p>Text editing and form shortcuts:</p>
      <div class="hotkey-grid">
        <div>
          <kbd>{{ formatForDisplay('Mod+Enter') }}</kbd> — Submit form
        </div>
        <div>
          <kbd>{{ formatForDisplay('Shift+Enter') }}</kbd> — New line
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+Backspace') }}</kbd> — Delete word
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+Delete') }}</kbd> — Delete forward
        </div>
        <div>
          <kbd>{{ formatForDisplay('Control+Tab') }}</kbd> — Next tab
        </div>
        <div>
          <kbd>{{ formatForDisplay('Shift+Tab') }}</kbd> — Previous field
        </div>
        <div>
          <kbd>{{ formatForDisplay('Mod+Space') }}</kbd> — Toggle
        </div>
      </div>
      <div class="counter">
        Editing keys triggered: {{ editingKeyCount() }}x
      </div>
      <pre class="code-block">
injectHotkey('Mod+Enter', () => submitForm())
injectHotkey('Shift+Enter', () => insertNewline())
injectHotkey('Mod+Backspace', () => deleteWord())
injectHotkey('Control+Tab', () => nextTab())
injectHotkey('Mod+Space', () => toggle())</pre
      >
    </section>

    @if (lastHotkey()) {
      <div class="info-box">
        <strong>Last triggered:</strong> {{ formatForDisplay(lastHotkey()!) }}
      </div>
    }

    <p class="hint">Press <kbd>Escape</kbd> to reset all counters</p>

    <section class="demo-section scoped-section">
      <h2>Scoped Keyboard Shortcuts</h2>
      <p>
        Shortcuts can be scoped to specific DOM elements using the
        <code>target</code> option. Use a getter for reactive targets (like
        Solid):
        <code
          >() =&gt; (&#123; target: this.sidebarRef()?.nativeElement ?? null
          &#125;)</code
        >
      </p>

      <div class="scoped-grid">
        <div class="scoped-area" #sidebarRef tabindex="0">
          <h3>Sidebar (Scoped Area)</h3>
          <p>Click here to focus, then try:</p>
          <div class="hotkey-list">
            <div>
              <kbd>{{ formatForDisplay('Mod+B') }}</kbd> — Trigger sidebar
              action
            </div>
            <div>
              <kbd>{{ formatForDisplay('Mod+N') }}</kbd> — New item
            </div>
          </div>
          <div class="counter">
            Sidebar shortcuts: {{ sidebarShortcutCount() }}x
          </div>
          <p class="hint">
            These shortcuts only work when this sidebar area is focused or
            contains focus.
          </p>
        </div>

        <div class="scoped-area">
          <h3>Modal Dialog</h3>
          <button type="button" (click)="openModal()">Open Modal</button>
          @if (modalOpen()) {
            <div class="modal-overlay" (click)="closeModalOverlay()">
              <div
                class="modal-content"
                #modalRef
                tabindex="0"
                (click)="onModalContentClick($event)"
              >
                <h3>Modal Dialog (Scoped)</h3>
                <p>Try these shortcuts while modal is open:</p>
                <div class="hotkey-list">
                  <div>
                    <kbd>{{ formatForDisplay('Escape') }}</kbd> — Close modal
                  </div>
                  <div>
                    <kbd>{{ formatForDisplay('Mod+Enter') }}</kbd> — Submit
                  </div>
                </div>
                <div class="counter">
                  Modal shortcuts: {{ modalShortcutCount() }}x
                </div>
                <p class="hint">
                  These shortcuts only work when the modal is open and focused.
                  The Escape key here won't conflict with the global Escape
                  handler.
                </p>
                <button type="button" (click)="closeModal()">Close</button>
              </div>
            </div>
          }
        </div>

        <div class="scoped-area">
          <h3>Text Editor (Scoped)</h3>
          <p>Focus the editor below and try:</p>
          <div class="hotkey-list">
            <div>
              <kbd>{{ formatForDisplay('Mod+S') }}</kbd> — Save editor content
            </div>
            <div>
              <kbd>{{ formatForDisplay('Mod+/') }}</kbd> — Add comment
            </div>
            <div>
              <kbd>{{ formatForDisplay('Mod+K') }}</kbd> — Clear editor
            </div>
          </div>
          <textarea
            #editorRef
            class="scoped-editor"
            [value]="editorContent()"
            (input)="onEditorInput($event)"
            placeholder="Focus here and try the shortcuts above..."
            rows="8"
          ></textarea>
          <div class="counter">
            Editor shortcuts: {{ editorShortcutCount() }}x
          </div>
          <p class="hint">
            These shortcuts only work when the editor is focused. Notice that
            <kbd>{{ formatForDisplay('Mod+S') }}</kbd> here doesn't conflict
            with the global <kbd>{{ formatForDisplay('Mod+S') }}</kbd> shortcut.
          </p>
        </div>
      </div>

      <pre class="code-block">
// Scoped to viewChild (Solid-style getter, like Solid's () =&gt; (&#123; target: ref() &#125;))
private readonly sidebarRef = viewChild&lt;ElementRef&lt;HTMLDivElement&gt;&gt;('sidebarRef')

injectHotkey(
  'Mod+B',
  () => console.log('Sidebar shortcut!'),
  () => (&#123; target: this.sidebarRef()?.nativeElement ?? null &#125;)
)

// Scoped to modal (only when open)
injectHotkey(
  'Escape',
  () => this.modalOpen.set(false),
  () => (&#123; target: this.modalRef()?.nativeElement ?? null, enabled: this.modalOpen() &#125;)
)

// Scoped to editor
injectHotkey(
  'Mod+S',
  () => saveEditorContent(),
  () => (&#123; target: this.editorRef()?.nativeElement ?? null &#125;)
)</pre
      >
    </section>
  </main>
</div>
