// examples/vue/useHotkeyRecorder/src/ShortcutListItem.vue
<script setup lang="ts">
import { formatForDisplay, useHeldKeys } from '@tanstack/vue-hotkeys'
import type { Hotkey } from '@tanstack/vue-hotkeys'

defineEmits<{
  edit: []
  cancel: []
}>()

defineProps<{
  actionName: string
  hotkey: string
  isRecording: boolean
}>()

const heldKeys = useHeldKeys()
</script>

<template>
  <div class="shortcut-item" :class="{ recording: isRecording }">
    <div class="shortcut-item-content">
      <div class="shortcut-action">{{ actionName }}</div>
      <div class="shortcut-hotkey">
        <div v-if="isRecording" class="recording-indicator">
          <div v-if="heldKeys.length > 0" class="held-hotkeys">
            <template v-for="(key, index) in heldKeys" :key="key">
              <span v-if="index > 0" class="plus">+</span>
              <kbd>{{ key }}</kbd>
            </template>
          </div>
          <span v-else class="recording-text"
            >Press any key combination...</span
          >
        </div>
        <kbd v-else-if="hotkey">{{ formatForDisplay(hotkey as Hotkey) }}</kbd>
        <span v-else class="no-shortcut">No shortcut</span>
      </div>
    </div>
    <div class="shortcut-actions">
      <button v-if="isRecording" class="cancel-button" @click="$emit('cancel')">
        Cancel
      </button>
      <button v-else class="edit-button" @click="$emit('edit')">Edit</button>
    </div>
  </div>
</template>

// examples/angular/injectHotkeyRecorder/src/app/shortcut-list-item.component.ts
import { Component, input, output } from '@angular/core'
import {
  formatForDisplay,
  formatKeyForDebuggingDisplay,
  injectHeldKeys,
} from '@tanstack/angular-hotkeys'

@Component({
  selector: 'app-shortcut-list-item',
  standalone: true,
  templateUrl: './shortcut-list-item.component.html',
  styleUrl: './shortcut-list-item.component.css',
})
export class ShortcutListItemComponent {
  actionName = input.required<string>()
  hotkey = input.required<string>()
  isRecording = input.required<boolean>()
  edit = output<void>()
  cancel = output<void>()

  heldKeys = injectHeldKeys()
  formatForDisplay = formatForDisplay
  formatKey = formatKeyForDebuggingDisplay
}

<div class="shortcut-item" [class.recording]="isRecording()">
  <div class="shortcut-item-content">
    <div class="shortcut-action">{{ actionName() }}</div>
    <div class="shortcut-hotkey">
      @if (isRecording()) {
        <div class="recording-indicator">
          @if (heldKeys().length > 0) {
            <div class="held-hotkeys">
              @for (key of heldKeys(); track key; let i = $index) {
                @if (i > 0) {
                  <span class="plus">+</span>
                }
                <kbd>{{ formatKey(key) }}</kbd>
              }
            </div>
          } @else {
            <span class="recording-text">Press any key combination...</span>
          }
        </div>
      } @else if (hotkey()) {
        <kbd>{{ formatForDisplay(hotkey()) }}</kbd>
      } @else {
        <span class="no-shortcut">No shortcut</span>
      }
    </div>
  </div>
  <div class="shortcut-actions">
    @if (isRecording()) {
      <button type="button" class="cancel-button" (click)="cancel.emit()">
        Cancel
      </button>
    } @else {
      <button type="button" class="edit-button" (click)="edit.emit()">
        Edit
      </button>
    }
  </div>
</div>
